const translations={
 it:{
  "nav.about":"Chi siamo","nav.duo":"Duo","nav.myday":"MyDay","nav.download":"Download","nav.contact":"Contatti",
  "hero.kicker":"Mobile apps • Giochi • Esperienze digitali","hero.title":"XVII Digital","hero.text":"Uno spazio indipendente dove idee mobile, giochi e prodotti digitali vengono progettati con cura, prototipati e portati lentamente verso il lancio.","hero.cta1":"Scopri i progetti","hero.cta2":"Scrivici",
  "about.kicker":"Chi siamo","about.title":"Un laboratorio digitale per nuove idee mobile.","about.text":"XVII Digital nasce per sviluppare prodotti digitali moderni, accessibili e scalabili. I primi progetti sono Duo, un gioco di parole competitivo, e MyDay, una social app pensata per condividere momenti autentici della giornata.",
  "about.a.title":"Prodotti propri","about.a.text":"Non un catalogo di servizi: il focus è creare e far crescere progetti digitali originali.","about.b.title":"Design riconoscibile","about.b.text":"Interfacce curate, dettagli premium, animazioni fluide e una forte identità visiva.","about.c.title":"Beta e feedback","about.c.text":"I prodotti vengono provati, migliorati e rifiniti prima di arrivare agli store ufficiali.",
  "duo.kicker":"Coming soon","duo.title":"Duo — il gioco di parole competitivo.","duo.intro":"Sfide rapide, parole, strategia e categorie sempre diverse. Duo è pensato per chi ama competere, allenarsi e battere gli amici una partita alla volta.","duo.panel.title":"Parole, duelli e party multiplayer.","duo.panel.text":"Duo unisce la semplicità dei giochi di parole alla tensione delle sfide in tempo reale: duelli casuali, stanze private, party fino a 4 giocatori, allenamento, classifiche, monete, aiuti, skin e modalità speciali.","duo.cta":"Disponibilità",
  "f1.title":"Sfide immediate","f1.text":"Entra in partita, trova l’avversario e gioca round veloci senza attese inutili.","f2.title":"Categorie dinamiche","f2.text":"La ruota sceglie il tema prima della sfida e rende ogni partita diversa.","f3.title":"Party con amici","f3.text":"Crea una stanza privata e invita fino a 4 giocatori per una sfida più sociale.","f4.title":"Progressione","f4.text":"Classifiche, monete, ricompense e personalizzazioni per far crescere il tuo profilo.",
  "myday.kicker":"Social app • Beta Android","myday.title":"MyDay — racconta la tua giornata, un momento alla volta.","myday.text":"MyDay è una social app costruita attorno alla giornata reale: condividi brevi Moments durante mattina, pomeriggio, sera e notte, scopri cosa succede nel mondo e segui le persone che vuoi avere nel tuo percorso quotidiano.","myday.feature1":"☀️ 4 momenti della giornata","myday.feature2":"🎥 Moments brevi e autentici","myday.feature3":"🌍 Discover & World","myday.feature4":"👤 Profili e giornate recenti","myday.ios":"Coming soon","myday.android":"Beta tester aperta","myday.beta.label":"Come partecipare alla beta Android","myday.beta.text":"Prima entra nel gruppo dei tester, poi apri Google Play e aderisci al programma di test.","myday.beta.group":"👥 1. Iscriviti al gruppo Beta","myday.beta.play":"▶ 2. Partecipa al test su Google Play",
  "download.badge":"Disponibilità","download.title":"Duo — beta Android disponibile.","download.text":"Su Android puoi già partecipare al programma beta ufficiale tramite Google Play. La versione per iPhone è in arrivo.","beta.title":"Partecipa alla beta Android","beta.text":"Per provare Duo su Android, iscriviti prima al gruppo ufficiale dei beta tester e poi accedi al programma di test direttamente da Google Play.","beta.group":"👥 1. Iscriviti al gruppo Beta","beta.play":"▶ 2. Partecipa al test su Google Play",
  "legal.kicker":"Risorse","legal.title":"Privacy, termini e informazioni utili.","legal.privacy":"Informazioni su dati, contatti, cookie e diritti privacy.","legal.terms":"Condizioni generali di utilizzo del sito e delle eventuali beta.",
  "contact.kicker":"Contatti","contact.title":"Informazioni e richieste.","contact.text":"Per informazioni generali, collaborazioni o richieste relative ai progetti XVII Digital, puoi utilizzare i contatti ufficiali indicati di seguito.","contact.cta":"Invia messaggio"
 },
 en:{
  "nav.about":"About","nav.duo":"Duo","nav.myday":"MyDay","nav.download":"Download","nav.contact":"Contact",
  "hero.kicker":"Mobile apps • Games • Digital experiences","hero.title":"XVII Digital","hero.text":"An independent space where mobile ideas, games and digital products are carefully designed, prototyped and slowly moved toward launch.","hero.cta1":"Explore projects","hero.cta2":"Contact us",
  "about.kicker":"About","about.title":"A digital lab for new mobile ideas.","about.text":"XVII Digital was created to develop modern, accessible and scalable digital products. The first projects are Duo, a competitive word game, and MyDay, a social app concept designed to share authentic moments of the day.",
  "about.a.title":"Own products","about.a.text":"Not a service catalogue: the focus is creating and growing original digital projects.","about.b.title":"Recognizable design","about.b.text":"Polished interfaces, premium details, smooth animations and a strong visual identity.","about.c.title":"Beta and feedback","about.c.text":"Products are tested, improved and refined before reaching the official stores.",
  "duo.kicker":"Coming soon","duo.title":"Duo — the competitive word game.","duo.intro":"Fast challenges, words, strategy and always-changing categories. Duo is designed for people who love competing, training and beating friends one match at a time.","duo.panel.title":"Words, duels and multiplayer parties.","duo.panel.text":"Duo combines the simplicity of word games with the tension of real-time challenges: random duels, private rooms, parties up to 4 players, training, rankings, coins, helpers, skins and special modes.","duo.cta":"Availability",
  "f1.title":"Instant matches","f1.text":"Jump in, find an opponent and play fast rounds without unnecessary waiting.","f2.title":"Dynamic categories","f2.text":"The wheel selects the theme before the challenge and makes every match different.","f3.title":"Party with friends","f3.text":"Create a private room and invite up to 4 players for a more social challenge.","f4.title":"Progression","f4.text":"Rankings, coins, rewards and customizations to grow your profile.",
  "myday.kicker":"Social app • Android Beta","myday.title":"MyDay — tell your day, one moment at a time.","myday.text":"MyDay is a social app built around real everyday life: share short Moments across morning, afternoon, evening and night, discover what is happening around the world and follow the people you want in your daily journey.","myday.feature1":"☀️ 4 parts of your day","myday.feature2":"🎥 Short, authentic Moments","myday.feature3":"🌍 Discover & World","myday.feature4":"👤 Profiles and recent days","myday.ios":"Coming soon","myday.android":"Beta testing open","myday.beta.label":"How to join the Android beta","myday.beta.text":"First join the testers group, then open Google Play and join the testing program.","myday.beta.group":"👥 1. Join the Beta group","myday.beta.play":"▶ 2. Join the test on Google Play",
  "download.badge":"Availability","download.title":"Duo — Android beta available.","download.text":"On Android you can already join the official beta program through Google Play. The iPhone version is coming soon.","beta.title":"Join the Android beta","beta.text":"To try Duo on Android, first join the official beta testers group, then access the testing program directly on Google Play.","beta.group":"👥 1. Join the Beta group","beta.play":"▶ 2. Join the test on Google Play",
  "legal.kicker":"Resources","legal.title":"Privacy, terms and useful information.","legal.privacy":"Information about data, contacts, cookies and privacy rights.","legal.terms":"General terms for the website and any beta releases.",
  "contact.kicker":"Contact","contact.title":"Information and requests.","contact.text":"For general information, collaborations or requests related to XVII Digital projects, you can use the official contacts listed below.","contact.cta":"Send message"
 }
};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function setLang(lang){document.documentElement.lang=lang;$$('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key])el.innerHTML=translations[lang][key]});$$('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('lang',lang)}
$$('.lang').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
$('.menu-toggle')?.addEventListener('click',()=>$('.nav').classList.toggle('open'));
$$('.nav a').forEach(a=>a.addEventListener('click',()=>$('.nav').classList.remove('open')));
$('#year').textContent=new Date().getFullYear();setLang(localStorage.getItem('lang')||'it');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
window.addEventListener('mousemove',e=>{const g=$('.cursor-glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
$$('.magnetic').forEach(btn=>btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)/10}px,${(e.clientY-r.top-r.height/2)/10}px)`}));$$('.magnetic').forEach(btn=>btn.addEventListener('mouseleave',()=>btn.style.transform=''));
